### PR TITLE
Added support for null `@Parcle` values

### PR DESCRIPTION
**Pull request by iainconnor**
Just a simple null check to avoid a crash.

### CODE REVIEW

**Comment by tom91136** [comment]
`Parcels.wrap()` handles null internally:

    public static <T> Parcelable wrap(Class<? extends T> inputType, T input) {
        if(input == null){
            return NULL_PARCELABLE;
        }
        ParcelableFactory parcelableFactory = REPOSITORY.get(inputType);

        return parcelableFactory.buildParcelable(input);
    }

What kind of crash are you seeing?

**Comment by iainconnor** [comment]
Happens in the class detection method

**Comment by tom91136** [comment]
Oh, I see

**Comment by tom91136** [comment]
This sort of things happens if I don't write tests for the plugins :( .
I'll consider adding some simple integration tests to make sure we don't have bugs like this.

**Comment by iainconnor** [comment]
Not a problem. Thanks for the quick reply and the work on this library!

**Pull request merged**
